-- HANA SCENT ARTIST analytics events
-- Run this file in Supabase SQL Editor before using /admin/analytics.html.

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  page text not null,
  event_type text not null,
  source text not null default 'Direct',
  result_type text,
  session_id text,
  path text,
  referrer text,
  user_agent text,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists analytics_events_created_at_idx on public.analytics_events (created_at desc);
create index if not exists analytics_events_page_event_idx on public.analytics_events (page, event_type, created_at desc);
create index if not exists analytics_events_source_idx on public.analytics_events (source, created_at desc);
create index if not exists analytics_events_result_type_idx on public.analytics_events (result_type, created_at desc);
create index if not exists analytics_events_session_idx on public.analytics_events (session_id, created_at desc);

alter table public.analytics_events enable row level security;

-- Public website visitors can insert tracking events only.
drop policy if exists "analytics_events_public_insert" on public.analytics_events;
create policy "analytics_events_public_insert"
on public.analytics_events
for insert
to anon, authenticated
with check (
  page in ('home','helori_quiz','helori_course','course_page','blog','journal','page')
  and event_type in ('view','click_helori','click_quiz','quiz_start','quiz_complete','click_line','click_discount','click_course','click_booking','share_quiz')
  and source in ('Instagram','LINE','Google','Direct','Other')
);

-- Logged-in CMS users can read dashboard data.
drop policy if exists "analytics_events_authenticated_read" on public.analytics_events;
create policy "analytics_events_authenticated_read"
on public.analytics_events
for select
to authenticated
using (true);
